version: '3'
services:

  postgres:
#    logging:
#      driver: journald
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: toosafinder
#      PGDATA: var/lib/postgresql/data/pgdata
#    volumes:
#      - /var/pgdata:/var/lib/postgresql/data/pgdata
#
#  app:
#    logging:
#      driver: journald
#    build:
#      context: "server"
#    environment:
#      - profile=$profile
#
#    restart: always
#    depends_on:
#      - postgres
#    links:
#      - "postgres:database"
#
#  nginx:
#    logging:
#      driver: journald
#    image: nginx:latest
#    volumes:
#      - ./nginx/etc/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/etc/certs:/etc/nginx/cert
#    ports:
#      - 443:443
#    links:
#      - app
