@startuml

Пользователь -> "Клиентское приложение" : email, логин, пароль
"Клиентское приложение" -> Сервер: 1. registerUser

alt email или логин заняты
    "Клиентское приложение" <-- Сервер: 1. User Duplication Error
    "Клиентское приложение" --> Пользователь: Сообщение об ошибке
else иначе
    Сервер -> Сервер: Сохраняет данные в БД
    Сервер -> "Почтовый сервер": Письмо со ссылкой в\nклиентское приложение
    alt Ошибка при отправке письма
        Сервер <-- "Почтовый сервер": Письмо со ссылкой в\nклиентское приложение
        "Клиентское приложение" <-- Сервер: 1. Mail Error
        Пользователь <-- "Клиентское приложение" : Сообщение об \nошибке при отправке письма
    else Письмо успешно отправлено
        Сервер <-- "Почтовый сервер": Письмо со ссылкой в\nклиентское приложение
        "Клиентское приложение" <-- Сервер: 1. Success
        Пользователь <-- "Клиентское приложение" : Сообщение об отправленном\n письме

        Пользователь -> "Клиентское приложение" : Переход по ссылке из письма

        "Клиентское приложение" -> Сервер: 2. confirmUser
        "Клиентское приложение" <-- Сервер
        Пользователь <-- "Клиентское приложение" : Форма авторизации
    end
end

@enduml
