@startuml

Пользователь -> "Клиентское приложение" : email, логин
"Клиентское приложение" -> Сервер: 1. Регистрация пользователя

alt email или логин заняты
    "Клиентское приложение" <-- Сервер: 1. User Duplication Error
    "Клиентское приложение" --> Пользователь: Сообщение об ошибке
else иначе
    Сервер -> Сервер: Сохраняет данные в БД
    Сервер -> "Почтовый сервер": Письмо со ссылкой в\nклиентское приложение
    alt Ошибка при отправке письма
        Сервер <-- "Почтовый сервер": Письмо со ссылкой в\nклиентское приложение
        "Клиентское приложение" <-- Сервер: 1. Mail Error
        Пользователь <-- "Клиентское приложение" : Сообщение об \nошибке при отправке письма
    else Письмо успешно отправлено
        Сервер <-- "Почтовый сервер": Письмо со ссылкой в\nклиентское приложение
        "Клиентское приложение" <-- Сервер: 1. Success
        Пользователь <-- "Клиентское приложение" : Сообщение об отправленном\n письме

        Пользователь -> "Клиентское приложение" : Переход по ссылке из письма
        Пользователь <-- "Клиентское приложение" : Форма создания пароля

        Пользователь -> "Клиентское приложение" : Пароль
        "Клиентское приложение" -> Сервер: 2. Регистрация пароля
        Сервер -> Сервер: Сохраняет пароль в БД
        "Клиентское приложение" <-- Сервер
        Пользователь <-- "Клиентское приложение" : Форма авторизации
    end
end

@enduml
